<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tests</RootNamespace>
        <Company>github.com/d-led</Company>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ApprovalTests" Version="7.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageReference Include="MSTest" Version="4.2.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AutoYnabCsv\AutoYnabCsv.csproj" />
    </ItemGroup>

</Project>
